### PR TITLE
Switched to the more performant System.Threading.Lock on .NET 9.0+

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**

### CODE REVIEW

**Comment by hamster620** [comment]
@MarkCiliaVincenti Thanks for the change, but we need to use ```NET9_0_OR_GREATER``` variable and use different implementation for net9.0 and older frameworks.

**Comment by MarkCiliaVincenti** [comment]
Are you referring to this please? <ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net9.0'))">

**Comment by MarkCiliaVincenti** [comment]
Are you referring to this please?

`<ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net9.0'))">`

**Comment by hamster620** [comment]
@MarkCiliaVincenti The code won't be compiled in net6.0/net7.0/net8.0. We need to use conditional implementation as the following:
```C#
#if NET9_0_OR_GREATER
    readonly Lock syncLock = new();
#endif

...

#if NET9_0_OR_GREATER
    lock (this.syncLock)
#else
    lock (this)
#endif
```

You can run ```BuildPackages.bat``` or ```BuildPackages.sh``` to perform full build to check, thanks.

**Comment by MarkCiliaVincenti** [comment]
The code as is compiles due to this added dependency:

````
	<ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net9.0'))">
		<PackageReference Include="Backport.System.Threading.Lock" Version="2.0.5" />
	</ItemGroup>
````

**Comment by hamster620** [comment]
> The code as is compiles due to this added dependency:
> 
> ```
> 	<ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net9.0'))">
> 		<PackageReference Include="Backport.System.Threading.Lock" Version="2.0.5" />
> 	</ItemGroup>
> ```

Oh sorry I didn't notice that. Seems a good way to handle this case, thanks.

**Pull request merged**
