### PR TITLE
add custom Referer 

### PR DESCRIPTION
**Pull request by Fsystem**
add Updater.SetExtraHeaders and WebRequestStreamProvider.SetExtraHeaders to set custom http request header

### CODE REVIEW

**Review by hamster620 — COMMENTED** [review]
Whats te purpose of setting ```ServicePointManager.ServerCertificateValidationCallback```?

**Comment by Fsystem** [comment]
ignore tls error when use Self-signed certificate

**Comment by hamster620** [comment]
> ignore tls error when use Self-signed certificate

It should be handled by AutoUpdater. I will implement this feature based-on your change.

**Comment by hamster620** [comment]
Close by alternative implementations:
- https://github.com/carina-studio/AppBase/commit/9d4e7fcf6100c695263a2bb5b016636e3244102f
- https://github.com/carina-studio/AppBase/commit/2a5faa60d839503ba0f2d70e466ab4cabde9d7ab
- https://github.com/carina-studio/AppBase/commit/cefb81a4d5d58c2b0f6f72334d108a186ff58e38

**Pull request closed without merging**
